### PR TITLE
Adjust "Details" and "Actions" columns in Scheduled Payments transactions list

### PR DESCRIPTION
**Pull request by lukemelia**
image

### CODE REVIEW

**Review by FadhlanR — APPROVED** [review]

**Review by jurgenwerk — APPROVED** [review]
Code looks good but for UI consistency I'd prefer to keep the dropdown trigger always displayed and disable the option inside it in case it doesn't apply.

**Comment by lukemelia** [comment]
>Code looks good but for UI consistency I'd prefer to keep the dropdown trigger always displayed and disable the option inside it in case it doesn't apply.

Sounds good. I'll make that change.

**Comment by lukemelia** [comment]
@jurgenwerk updated. have another look

**Review by jurgenwerk — APPROVED** [review]
👍

**Pull request merged**
