### PR TITLE
[CS-1511]: Add check-version function

### PR DESCRIPTION
**Pull request by danibonilha**
Adds checkVersion firebase function 

image

image

### CODE REVIEW

**Review by lukemelia — COMMENTED** [review]
Overall, looks good. I notice that the PR includes a yarn lockfile at `packages/firebase-functions/check-version/functions/yarn.lock`. None of the other packages in the repository have a lockfile -- I think this is because they use the one at the root as part of how yarn workspaces work. Is there a reason that this package would be different?

**Comment by danibonilha** [comment]
> Overall, looks good. I notice that the PR includes a yarn lockfile at `packages/firebase-functions/check-version/functions/yarn.lock`. None of the other packages in the repository have a lockfile -- I think this is because they use the one at the root as part of how yarn workspaces work. Is there a reason that this package would be different?

Good catch, it seems lerna path is not configured correctly for nested paths, I'll add a fix = )

**Comment by lukemelia** [comment]
@danibonilha Should the yarn.lock file be removed from the PR then?

**Comment by danibonilha** [comment]
@lukemelia I've removed the nested yarn.lock, the one changed in this PR is the root one, adding the firebase dependencies.

**Review by habdelra — APPROVED** [review]
looks good to me 👍

**Pull request merged**
