### PR TITLE
Refactor hub to use yargs

### PR DESCRIPTION
**Pull request by mattmcmanus**
This is a pretty straightforward first step. There is more room for refactoring, but we can hold off. 

One complicating factor is that we have config coming from everywhere. `dotenv`, `node-config`, and now the option to pass in some via `yargs`. `node-config` does not play nice with others, but the current status-quo seems to work fine.

I'd like to integrate the `--verbose` option into our loggers, but I haven't fully grokked @cardstack/logger yet. 

#### Example output
```➜ bin/hub --help
hub <command>

Commands:
  hub console       Load up a REPL
  hub db <command>  Commands to manage the local database
  hub serve         Boot the server                            [aliases: server]
  hub worker        Boot the worker

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]
```

```
➜ bin/hub db --help
hub db <command>

Commands to manage the local database

Commands:
  hub db dump       Dump a structure.sql file to be used to init the test
                    database
  hub db init-test  Create the test database using the ENVs config
  hub db seed       Seed the database from ./db/seeds
  hub db setup      Initialize your local database

Options:
  --version  Show version number                                       [boolean]
  --help     Show help
```

### CODE REVIEW

**Review by lukemelia — APPROVED** [review]
Nice improvement. OK by me once the CI issue is fixed and you do a once over of the README to update any docs that needs updating.

**Comment by mattmcmanus** [comment]
@lukemelia I updated the README a bunch. Curious what you think.

**Comment by lukemelia** [comment]
@mattmcmanus Nice improvements. TOC is a great touch.

**Comment by lukemelia** [comment]
@mattmcmanus Nice improvements. TOC is a great touch.

**Pull request merged**
