### PR TITLE
Refactor and update tx-amount cards

### PR DESCRIPTION
**Pull request by burieberry**
- This is extracted from a larger branch (created sub-issue [CS-1270](https://linear.app/cardstack/issue/CS-1270/remove-approval-card-and-update-amount-card) for it)
- Remove approval card from the withdrawal workflow and integrate approval process to the amount card
- Amount card updates from the script and refactor

### CODE REVIEW

**Comment by burieberry** [comment]
@backspace I did this work last week, and didn't realize your input validation work also involved the same refactor. I resolved the merge conflicts, but there might be some auto-merge errors. Also I updated the validation messages to what I know. If Chris or somebody else had sent the new versions, I can revert. The validation message only needs to appear under the input field.

**Review by lukemelia — APPROVED** [review]
LGTM, pending @backspace's input on the merge

**Review by backspace — APPROVED** [review]
👍🏻 the merge looks good to me, I was able to try out deposit and withdrawal locally successfully with the amount input still working as expected (except for the withdrawal confirmation step as Card Wallet is currently broken for me). Nice to see some of this duplication removed! re the validation messages, those were suggestions from M, is there a place these are specified, for future reference?

**Comment by burieberry** [comment]
> 👍🏻 the merge looks good to me, I was able to try out deposit and withdrawal locally successfully with the amount input still working as expected (except for the withdrawal confirmation step as Card Wallet is currently broken for me). Nice to see some of this duplication removed! re the validation messages, those were suggestions from M, is there a place these are specified, for future reference?

No worries, I think they're kinda all over the place right now in various spreadsheets/versions of xd file if they even exist. Normally we would have Katrin go over them and put it all in one place.

**Pull request merged**
