### PR TITLE
Avoid issue where Infura is 1 block behind the chain head

### PR DESCRIPTION
**Pull request by jurgenwerk**
Ticket: [CS-2391](https://linear.app/cardstack/issue/CS-2391)

Check the discussion in the ticket. I did some testing and I believe this fixes the issue.

### CODE REVIEW

**Comment by jurgenwerk** [comment]
@habdelra here's my solution. Do you think it would be better to solve this in the sdk?

**Comment by habdelra** [comment]
We do have an API in the SDK that performs this same logic. (in the Assets.getBalanceForToken). I think this was originally written before that API existed. I just updated that API using your strategy

**Comment by habdelra** [comment]
ok @jurgenwerk, my changes are in now as well. how do they look to you?

**Comment by habdelra** [comment]
oh i spotted one more thing I want to do: to be consistent in our testing env, we should also wait one extra block in kovan (even though we dont' see the errors there)

**Review by habdelra — APPROVED** [review]
👍

**Comment by habdelra** [comment]
@jurgenwerk I approved it, but i think you should approve my changes as well

**Comment by habdelra** [comment]
@jurgenwerk I approved it, but i think you should approve my changes as well

**Comment by jurgenwerk** [comment]
@habdelra changes look good! One other thing I wanna do - I'm gonna try to use the assets api in layer1 chain in `refreshBalances` so that we don't repeat the `getBlockNumber` logic. Will finish that tomorrow morning but this can be merged now if really needed.

**Comment by habdelra** [comment]
i'm totally fine waiting until tomorrow for you to complete the work

**Comment by lukemelia** [comment]
@habdelra with @jurgenwerk's blessing, I finished up the work on this. Can you give it quick look-see and then we can get it merged?

**Comment by habdelra** [comment]
@lukemelia looks good. it would be nice, though, to have @jurgenwerk re-run his script to try to reproduce the bug again with these changes. but i don't think that has to stop us from merging this.

**Comment by jurgenwerk** [comment]
I've been running my stress test on prod and I can't reproduce the bug anymore. Thanks @habdelra and @lukemelia! 🎉

**Pull request merged**
