### PR TITLE
how to emit events that correspond with Operations

### PR DESCRIPTION
**Pull request by ef4**
@habdelra this should be all you need to emit events that correspond to the real indexer operations. I would rather do this than rely on making event consumers understand hints.

### CODE REVIEW

**Comment by habdelra** [comment]
sweet thanks! I'll merge this into the PR

**Comment by ef4** [comment]
I will add the classic Donald Knuth quote here: "Note that I have not tested this code, I have merely proven it correct". 😁

**Comment by habdelra** [comment]
no prob, I'm happy to do that

**Comment by habdelra** [comment]
closing this as it's served it's purpose and integrated into https://github.com/cardstack/cardstack/pull/99

**Pull request closed without merging**
