### PR TITLE
3 - Add reward program lock and update reward program admin in SDK 

### PR DESCRIPTION
**Pull request by tintinthong**
- add `lockRewardProgram` and `isRewardProgramLocked`
- add `updateRewardProgramAdmin` and `rewardProgramAdmin`

`updateRewardProgramAdmin` will work as normal. `lockRewardProgram` will be affected by next card pay deploy (but its ok to merge first bcos its just a state variable) .

### CODE REVIEW

**Comment by habdelra** [comment]
I'd like to propose that we start splitting out the PrepaidCardManager's base.ts. It feels like it's losing cohesion in that is is doing _a lot_ of different things, and the file size is getting pretty large. let's create a new SDK for the reward related prepaid card actions, as then split out any common functionality between the PrepaidCardManager and the new SDK so that both these modules can share.

**Review by habdelra — COMMENTED** [review]
Let's create a new SDK for rewards related prepaid card actions

**Comment by tintinthong** [comment]
Ok I'll add a refactor for that

**Comment by tintinthong** [comment]
Also this is not a blocking pr for simple rewards.

**Comment by tintinthong** [comment]
> I'd like to propose that we start splitting out the PrepaidCardManager's base.ts. It feels like it's losing cohesion in that is is doing a lot of different things, and the file size is getting pretty large. let's create a new SDK for the reward related prepaid card actions, as then split out any common functionality between the PrepaidCardManager and the new SDK so that both these modules can share.

Actually, wouldn't it be better to just move the prepaid card actions into the reward manager base since it is not that big at all. And the prepaid card actions for rewards do correspond to reward manager logic. Its more straightforward change.

**Comment by tintinthong** [comment]
A deeper refactor perhaps is more appropriate in a different pr.

**Comment by tintinthong** [comment]
this pr can go in before protocol deploy.

**Comment by habdelra** [comment]
> Actually, wouldn't it be better to just move the prepaid card actions for rewards into the reward manager base (similar to prepaid card market is organised) since it is not that big at all. And the prepaid card actions for rewards do correspond to reward manager logic. Its more straightforward change.

yeah that sounds just fine.

**Review by habdelra — APPROVED** [review]
This looks very good. you'll just need to merge upstream changes into this PR and resolve the conflicts

**Pull request merged**
