### PR TITLE
Fix description for `rewards transfer-safe` command

### PR DESCRIPTION
**Pull request by jurgenwerk**
Probably a copy/paste remnant.

### CODE REVIEW

**Comment by tintinthong** [comment]
So @jurgenwerk I think the docs for cli is sourced from the command file [here](https://github.com/cardstack/cardstack/pull/2847/files). So you'd need to edit this file and the run `yarn command-docs` to generate the markdown of the readme.

**Comment by jurgenwerk** [comment]
@tintinthong thanks! I changed the description in the command file instead, and regenerated the readme using `yarn command-docs`. For this to work I first needed to run `yarn prepack` in the `packages/cardpay-sdk`. Do you it's worth noting this somewhere?

**Comment by tintinthong** [comment]
> @tintinthong thanks! I changed the description in the command file instead, and regenerated the readme using `yarn command-docs`. For this to work I first needed to run `yarn prepack` in the `packages/cardpay-sdk`. Do you it's worth noting this somewhere?

I believe `yarn prepack` is specified in the README.md of the cardpay-cli package.

**Review by lukemelia — APPROVED** [review]
Thanks!

**Pull request merged**
