### PR TITLE
Enhancement/refactor web client tokens

### PR DESCRIPTION
**Pull request by Aierie**
CS-765

- Refactors tokens to use a set of utils and types defined centrally
- Separates responsibility for presentational information (`TokenDisplayInfo`) and contract-related information (`TokenContractInfo`) for tokens

### CODE REVIEW

**Review by lukemelia — APPROVED** [review]
Good cleanup. Did you consider unifying TokenContractInfo and TokenDisplayInfo?

**Comment by Aierie** [comment]
> Good cleanup. Did you consider unifying TokenContractInfo and TokenDisplayInfo?

Thanks @lukemelia! I did. But decided to leave them separate because: 

1. right now, it looks like display info is not used where contract info is used and vice versa
2. the addresses for contracts are network-specific, and I couldn't think of a great way to introduce addresses as optional that wouldn't reduce the Typescript benefits for the contract side.
3. Tokens like eth that we have some display information for are not used the same way as bridgeable tokens.

Did you have a structure in mind that would combine the two nicely?

**Comment by Aierie** [comment]
Possibly a `Token` class that has a `contractFor` method that returns a `TokenContractInfo` instance for a specific network, but otherwise behaves like a `TokenDisplayInfo` class?

**Comment by Aierie** [comment]
Merging first. May follow up if can think of a good way to combine contract and display info for tokens.

**Pull request merged**
