### PR TITLE
Add subgraph extraction package

### PR DESCRIPTION
**Pull request by lukemelia**

### CODE REVIEW

**Comment by IanCal** [comment]
Waypoint issue deploying this twice - the first succeeded
  
    The deploy was successful! A Waypoint deployment URL is shown below. This
    can be used internally to check your deployment and is not meant for external
    traffic. You can manage this hostname using "waypoint hostname."
    
               URL: https://***.waypoint.run
    Deployment URL: https://***.waypoint.run
    
    $ waypoint deploy -app=cardpay-subgraph-extraction 
    
    » Deploying...
    ✓ Found existing ECS cluster: cardpay-staging-subgraph-extraction
    ✓ Found existing IAM role to use: ecr-cardpay-subgraph-extraction
    ✓ Found task IAM role to use: cardpay-staging-subgraph-extraction-ecr-task
    ✓ Registered Task definition: waypoint-cardpay-subgraph-extraction
    ✓ Configured security group: cardpay-subgraph-extraction-inbound-internal
    ❌ Creating ECS Service (cardpay-subgraph-extraction-01FT, cluster-name: cardpay-staging-subgraph-extraction)
    ! InvalidParameterException: Creation of service was not idempotent.

**Comment by tintinthong** [comment]
May take me awhile to review. Im waiting for my local graph node to reindex. Who knows how long this will take. I'll leave some comments if I have any

**Comment by tintinthong** [comment]
May take me awhile for the review. I am reindexing my local graph node. Dono how long it will take. Will leave comments if any.

**Comment by tintinthong** [comment]
Ok to what extent do I need to update the config "manually". 

```
name: test_config
subgraph: habdelra/cardpay-sokol
tables:
  account:
    partition_column: id
    partition_sizes:
    - 32768
version: 0.0.1
```

exporting this yields 

```
Traceback (most recent call last):
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/bin/subgraph_config_generator", line 8, in <module>
    sys.exit(config_generator())
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/subgraph_extractor/cli.py", line 358, in config_generator
    schema_data = subgraph_table_schemas[options[menu_entry_index]]
TypeError: list indices must be integers or slices, not NoneType
(cardpay-subgraph) tintinthong@Justins-MacBook-Pro cardpay-subgraph-extraction % python export.py --database-string postgresql://username:password@localhost:5432/graph-node                                                   

Traceback (most recent call last):                                                                                                   
  File "/Users/tintinthong/Documents/GitHub/cardstack/packages/cardpay-subgraph-extraction/export.py", line 30, in <module>          
    export()
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/tintinthong/Documents/GitHub/cardstack/packages/cardpay-subgraph-extraction/export.py", line 23, in export
    extract_from_config(
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/subgraph_extractor/cli.py", line 244, in extract_from_config
    unexported_partitions = filter_existing_partitions(table_dir, partition_range)
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/subgraph_extractor/cli.py", line 197, in filter_existing_partitions
    for partition in sorted(partitions, reverse=True, key=lambda x: x[1]):
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/subgraph_extractor/cli.py", line 177, in get_partitions
    min_partition = int(limits_df["min_partition"].iloc[0])
ValueError: invalid literal for int() with base 10: '0x02096f0e711c6e1e855caf79273a05257B99e9F2'
```

**Comment by tintinthong** [comment]
```
name: test_config
subgraph: habdelra/cardpay-sokol
tables:
  account:
    partition_column: block_range
    partition_sizes:
    - 32768
version: 0.0.1
```
yields 

```
(cardpay-subgraph) tintinthong@Justins-MacBook-Pro cardpay-subgraph-extraction % python export.py --database-string postgresql://username:password@localhost:5432/graph-node      

Traceback (most recent call last):                                                                                                   
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedFunction: function min(int4range) does not exist
LINE 1: select min(block_range) as min_partition, max(block_range) a...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tintinthong/Documents/GitHub/cardstack/packages/cardpay-subgraph-extraction/export.py", line 30, in <module>
    export()
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/tintinthong/Documents/GitHub/cardstack/packages/cardpay-subgraph-extraction/export.py", line 23, in export
    extract_from_config(
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/subgraph_extractor/cli.py", line 244, in extract_from_config
    unexported_partitions = filter_existing_partitions(table_dir, partition_range)
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/subgraph_extractor/cli.py", line 197, in filter_existing_partitions
    for partition in sorted(partitions, reverse=True, key=lambda x: x[1]):
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/subgraph_extractor/cli.py", line 172, in get_partitions
    limits_df = pandas.read_sql(
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/pandas/io/sql.py", line 592, in read_sql
    return pandas_sql.read_query(
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/pandas/io/sql.py", line 1554, in read_query
    result = self.execute(*args)
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/pandas/io/sql.py", line 1399, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
  File "<string>", line 2, in execute
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 401, in warned
    return fn(*args, **kwargs)
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3146, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1274, in execute
    return self._exec_driver_sql(
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1578, in _exec_driver_sql
    ret = self._execute_context(
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/Users/tintinthong/opt/miniconda3/envs/cardpay-subgraph/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) function min(int4range) does not exist
LINE 1: select min(block_range) as min_partition, max(block_range) a...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

```

**Comment by tintinthong** [comment]
This works tho 

```
name: test_config
subgraph: habdelra/cardpay-sokol
tables:
  account:
    partition_column: vid
    partition_sizes:
    - 32768
version: 0.0.1
```

**Comment by tintinthong** [comment]
Shoot. Realise that I might not have pulled most recent. Lemme double check

**Comment by IanCal** [comment]
@tintinthong You'll want to partition on a block number most likely, a postgres range is changeable and not clearly splittable. Can't remember what vid is.

**Comment by IanCal** [comment]
Deployment issue should be fixed now there's a shorter app name

https://github.com/hashicorp/waypoint/issues/2957

**Comment by IanCal** [comment]
@lukemelia I think this is complete. There's now environment overrides & I've added how to deploy without having to use the prune script (in this case it's safe to have an older & newer version running side by side for a short time so no issues there, and keeping a rollback-able version isn't that important).

**Pull request merged**
