### PR TITLE
Implement first version of Layer 2 Connect modal

### PR DESCRIPTION
**Pull request by lukemelia**
CS-532

See Linear card for checklist

### CODE REVIEW

**Comment by lukemelia** [comment]
Screenshot 2021-04-08 at 12 51 15 PM

**Comment by lukemelia** [comment]
Note that I decided to create separate Linear cards for the video, "text it to me" and alternate xDai wallet features.

**Review by Aierie — COMMENTED** [review]
I'm having trouble building for some reason (even on main) so I'll have to look at the built product more closely after I debug that. Overall this looks fine to me! 

Minor detail: If we're focusing on using `rem` units, we might want to get our `img` tags and `canvas` to use them so that proportions are maintained if users change their root font sizes - but then how designs change with font size seems like a gray area, so I think it's fine if some parts aren't `rem`-ified for now.

**Comment by lukemelia** [comment]
> Minor detail: If we're focusing on using rem units, we might want to get our img tags and canvas to use them so that proportions are maintained if users change their root font sizes - but then how designs change with font size seems like a gray area, so I think it's fine if some parts aren't rem-ified for now.

@Aierie img tags can likely be styled with rems, although you will end up with subpixel rendering for bitmap images, so that's a tradeoff. Canvas is a bitmap concept, so AFAIK there is no direct way to use rems to size elements on a canvas, or the canvas itself.

**Comment by Aierie** [comment]
> > Minor detail: If we're focusing on using rem units, we might want to get our img tags and canvas to use them so that proportions are maintained if users change their root font sizes - but then how designs change with font size seems like a gray area, so I think it's fine if some parts aren't rem-ified for now.
> 
> @Aierie img tags can likely be styled with rems, although you will end up with subpixel rendering for bitmap images, so that's a tradeoff. Canvas is a bitmap concept, so AFAIK there is no direct way to use rems to size elements on a canvas, or the canvas itself.

@lukemelia Ah right bitmap is an issue. Canvas can be styled with css with rems, and the contents will resize to fit - but again bitmap will be an issue.

**Pull request merged**
