### PR TITLE
Organize creation of safes + customizations

### PR DESCRIPTION
**Pull request by Aierie**
Adds basic factory functions for creation of mock safes and prepaid card customizations + utilities and constants for handling the relationship between mock prepaid card customizations and their DIDs.

### CODE REVIEW

**Review by lukemelia — CHANGES_REQUESTED** [review]
Nice cleanup. One change I'd like to see: rename `tests/helpers/mocks.ts` to `tests/helpers/factories.ts` because it technically contains factories, not mocks.

**Review by backspace — APPROVED** [review]
I’ve been wishing for something like this for a while, thanks for tackling it 🤩

**Review by burieberry — APPROVED** [review]
Great!

**Comment by jurgenwerk** [comment]
Great! The other day [my commit](https://github.com/cardstack/cardstack/commit/c461428413308e85d49962eb617bff9d07ba572d#diff-f1389a55f87a1d879865be77af5d51dbfa539ff83abb15eefacc955d43af39c6) landed in main where I introduce a workflow stub but now I think it should be a factory as well.

**Review by jurgenwerk — APPROVED** [review]

**Pull request merged**
