### PR TITLE
Add option to hide model fields from editor

### PR DESCRIPTION
**Pull request by burieberry**

### CODE REVIEW

**Comment by balinterdi** [comment]
I like the approach but it would be great if we could default the `editorModelField` to true so that we don't have to explicitly set it everywhere (assuming we want to retain the current functionality of showing the field in the editor by default).

**Comment by burieberry** [comment]
@balinterdi yeah I can do that

**Comment by balinterdi** [comment]
@burieberry Looks good to me. The only thing I'd change is to only hide one normal and one computed field. We don't gain by hiding most of them and they can be useful to test other things.

And a question: why the `echo-` prefix? :)

**Comment by burieberry** [comment]
@balinterdi You're right, removed the extra tests. Ha I've seen someone else use the prefix in some other tests on this repo

**Comment by balinterdi** [comment]
> Ha I've seen someone else use the prefix in some other tests on this repo

Seem redundant/potentially confusing, can you remove them?

**Comment by burieberry** [comment]
Changed the field names. I added two new fields to test this because I didn't want to disturb the existing tests and it's good to have the examples in the dummy app.

**Pull request merged**
