### PR TITLE
1 - Update register rewardee sdk function and subgraph event 

### PR DESCRIPTION
**Pull request by tintinthong**
- `registerRewardee` uses prepaid card to pay for gas not fees -- the gas policy has changed.
- this is an sdk update to update the sdk function
- I removed indexing `registerRewardeeHandler` and the event `RewardeeRegistrationFees`

### CODE REVIEW

**Comment by tintinthong** [comment]
@habdelra I think there is no abis to update here for the sdk right https://github.com/cardstack/card-pay-protocol/pull/134/files?

**Comment by habdelra** [comment]
Confirm, this PR doesn’t change the ABIs that the SDK uses.

**Comment by tintinthong** [comment]
I think this can go in first. Tho not tested on NEW sokol protocol, this works for our CURRENT sokol protocol. The subgraph change is merely a removal of an indexing contract.

**Review by habdelra — APPROVED** [review]
Looks good

**Pull request merged**
