### PR TITLE
Fix fetchPermissions response destructuring for non-200 case

### PR DESCRIPTION
**Pull request by balinterdi**
See #635

### CODE REVIEW

**Comment by ef4** [comment]
Does this move the problem up to the caller?

It may still be reasonable to reject the promise instead, but with a more sensible error message than the current runtime exception.

**Comment by balinterdi** [comment]
I can do that, I have only one slight concern.

If I return a rejected promise with a descriptive error message (in this case informing the caller that the content-type doesn't exist) doesn't that give away (slightly) confidential information about what content-types we have? (and thus increase the surface area of a potential attack).

I'm reasonably sure that trade-off is worth it (app developers will benefit) but I just wanted to mention this.

**Comment by ef4** [comment]
I agree that information leakage is a concern, but this is client-side code, it's not relevant here.

**Comment by balinterdi** [comment]
@ef4 Could you check again?

**Pull request merged**
