### PR TITLE
mock token to usd

### PR DESCRIPTION
**Pull request by Aierie**
We need a way to convert tokens to USD for #1591 and #1584. This attempts to do that using a helper + a service that manages exchange rates.

### CODE REVIEW

**Comment by Aierie** [comment]
As this is only a mock prior to @habdelra finishing the API for getting exchange rates, will hardcode static values for this implementation.

**Comment by habdelra** [comment]
sure, ultimately you'll query the blockchain instead of a web service for the rates, as CARD token rates will only be available to us via the blockchain. and as such I'll be adding a new API in the cardpay-sdk to obtain these.

**Comment by habdelra** [comment]
This does imply that you have to connect to your wallet before any kind of rate information is available to the UI (since the wallet provides the gateway to make queries to the blockchain). I'm not sure if this causes you grief. it does mean that if you want to use an Ember service you'll need to consider 2 states since ember services have a lifetime that begins when the app boots: 
1. before the wallet is connected
2. after the wallet is connected

**Comment by Aierie** [comment]
> This does imply that you have to connect to your wallet before any kind of rate information is available to the UI (since the wallet provides the gateway to make queries to the blockchain). I'm not sure if this causes you grief. it does mean that if you want to use an Ember service you'll need to consider 2 states since ember services have a lifetime that begins when the app boots:
> 
> 1. before the wallet is connected
> 2. after the wallet is connected

Good to know, thanks @habdelra!

**Comment by Aierie** [comment]
Closing temporarily, since API PR is up. Will reopen after it's merged.

**Pull request closed without merging**
