### PR TITLE
hub: Add Firebase config for deployments

### PR DESCRIPTION
**Pull request by backspace**
Assumption: there isn’t separate configuration for staging
and production.

I haven’t yet found and entered the values for these in the repository settings 🔍

### CODE REVIEW

**Review by danibonilha — APPROVED** [review]
Yeah, I think in order to split into stag/prod we would need to have two diff firebase projects

**Comment by backspace** [comment]
maybe it doesn’t matter? I’m unsure of the implications of this. There are some environment variables that have `STAGING_` and `PRODUCTION_` prefixes, others don’t.

**Comment by backspace** [comment]
@jurgenwerk do you know what the configuration values are for these? I found the project id but I don’t know where to find the others 😯

**Comment by backspace** [comment]
maybe we figured it out 🤔

**Pull request merged**
