### PR TITLE
web: Extract CardPay::MerchantLogo component

### PR DESCRIPTION
**Pull request by backspace**
I need to be able to use this separately in #2038.

Left is with this change, right is `main`:

image

### CODE REVIEW

**Review by Aierie — APPROVED** [review]
This looks good. Separating a CSS circle as its own component does mean that it is subject to use in containers that it doesn't fit in, and can end up being squished in:

image

Not a big deal for now (this was artificially contorted), but something to be aware of I think.

**Comment by backspace** [comment]
hmm 😳  do you think there’s a way to mitigate this?

**Comment by Aierie** [comment]
> hmm 😳 do you think there’s a way to mitigate this?

I have only ever briefly thought about it, so not very sure about all the situations where this could happen. I think the most common cause would be `flex-shrink`.

**Comment by backspace** [comment]
okay, well hopefully there’s a way to deal if it comes up hehe thx

**Pull request merged**
