### PR TITLE
web: Add nonce-preservation for merchant creation

### PR DESCRIPTION
**Pull request by backspace**
This almost entirely copied from the implementation in
#1890.

screencast 2021-08-27 13-47-24

### CODE REVIEW

**Review by Aierie — APPROVED** [review]
The UI functions as expected!

However in testing this, I realised there are probably some details to work out for canceling transactions in general - canceling the transaction doesn't prevent the user from pressing "confirm" on Card Wallet and creating a merchant.

**Comment by Aierie** [comment]
https://linear.app/cardstack/issue/CS-1714/user-canceling-transaction-from-dapp-still-allows-confirming-of

**Review by lukemelia — APPROVED** [review]
It would be interesting to see if we can think of a way to extract this pattern for easier re-use. There's no obvious approach to me, though.

**Comment by backspace** [comment]
ya I’d love for this to be generalisable but it wasn’t obvious to me either, if it comes up a third time I’ll see about extraction possibilities

**Pull request merged**
