### PR TITLE
yarn.lock was updated

### PR DESCRIPTION
**Pull request by habdelra**

### CODE REVIEW

**Comment by backspace** [comment]
These changes keep coming up, it’s puzzling; what Yarn version are you on?

**Comment by habdelra** [comment]
```sh
$ yarn --version                     
1.22.5
```

**Comment by backspace** [comment]
hmm, maybe that’s why; we use Volta, which in the root `package.json` is locked to 1.22.10!

**Comment by habdelra** [comment]
let me try that

**Comment by habdelra** [comment]
@backspace so using the volta managed yarn I still end up with teh same lock file as is in this PR:
```sh
cardstack on yarn-lock-update-12-2-21 took 39s 
$ which yarn    
/Users/hassan/.volta/bin/yarn

cardstack on yarn-lock-update-12-2-21 
$ volta install yarn
success: installed and set yarn@1.22.15 as default
   note: you are using yarn@1.22.10 in the current project
```

**Comment by backspace** [comment]
hmm, then the mystery continues, we keep flipping back between these two changes 😞

**Comment by habdelra** [comment]
@backspace when you run `yarn install` in this branch, do you end up with the same lock file?

**Comment by backspace** [comment]
yes. Hopefully this is the last time this needs to happen then 🤞🏻

**Pull request merged**
