### PR TITLE
Refactor SDK args (onTxnHash, nonce, onNonce) to a single TransactionOptions arg

### PR DESCRIPTION
**Pull request by lukemelia**
- this is a BREAKING change to the SDK's API
- this prepares for the future addition of a txnHash option

Once merged cardstack/cardwallet will need an update here:
 https://github.com/cardstack/cardwallet/blob/develop/cardstack/src/screens/SendSheetDepot.tsx#L253-L255

### CODE REVIEW

**Comment by habdelra** [comment]
I'm ok with collapsing the various params into a single pojo, but I'm not sure that we actually want to have the txnHash in here too--as just providing a txnHash means that you don't actually need to provide any other param. otherwise what does it mean if you provide a txnHash, a nonce, and a safeAddress? it's a little more difficult divining the caller's intent when you can pass params that don't necessarily go together. let's use TS function overloading instead so that we can provide clear groupings of params that work together and we can more clearly determine the caller's intent.

**Comment by lukemelia** [comment]
Great point! I'll refactor accordingly.

**Comment by lukemelia** [comment]
@habdelra Looks like all the overload changes will be in #2053. OK to merge this one now?

**Review by habdelra — APPROVED** [review]
👍  looks good to merge

**Pull request merged**
