### PR TITLE
Restore missing field icons

### PR DESCRIPTION
**Pull request by jenweber**
Closes issue #1474

This PR adds back in the missing field icons. This is accomplished on the front end as a stopgap until icons become part of the Card API.

@burieberry the thing I could use your help with is figuring out how to visually balance the icons.

I also don't have an SVG for the input, and the text icon is different than what we had in the past. Do you have those assets anywhere?

### CODE REVIEW

**Comment by burieberry** [comment]
@jenweber yes, there are two different text icons. The icons I used for fields are in `/images/field-types` folder. I pushed some suggestions to your branch. I think the text icon actually needs to be 12px x 15px for the field-renderer, though. Feel free to make any changes

**Comment by burieberry** [comment]
@jenweber we can use `has-many-field-icon.svg` for the card field. It's not used anywhere else. We can rename it

**Comment by jenweber** [comment]
Something still isn't right here for the Chrome snapshots in Percy. It looks fine in Chrome on my computer. I added animation waiters and it had no effect.

Screen Shot 2020-03-31 at 10 25 27 AM

**Comment by burieberry** [comment]
@jenweber I see this issue visible on Safari and adding `max-width: 100%` to the `.ch-catalog-field--icon` class seems to work

**Pull request merged**
