### PR TITLE
Add ability to search all card types at once

### PR DESCRIPTION
**Pull request by mansona**
Adding an endpoint that allows you to query all card types at once.

This is a special case that essentially removes the `type` definition from the filter in the case that the type name is `all`

This allows for the ability to write: http://localhost:3000/api/all?q=testing which will query all types.

### Questions/Comments

- [x] This opens up the ability to GET http://localhost:3000/api/all and essentially list all cards without having to know the type name ahead of time. If this is an issue I can add a restriction so that you can only use this endpoint if you have specified a query string using `?q=`

### CODE REVIEW

**Comment by ef4** [comment]
I had forgotten that this didn't already exist. 😀

I'm not concerned with hiding the types, that's what the grants system is for. 

Right now the endpoint `/api` doesn't do anything useful, can we move this to there?

**Comment by mansona** [comment]
So I quickly added what you suggested, so now you can either query http://localhost:3000/api/all or http://localhost:3000/api and they will act the same way.

It may seem a little convoluted but I was going for maximum reuse, instead of trying to keep a generic `handleCollectionGET` and `handleCollectionGETAllTypes` in sync.

let me know your thoughts on the implementation and I'll adjust to your liking 👍

**Comment by ef4** [comment]
@mansona notice that I only kept the /api endpoint, not /api/all.

**Comment by ef4** [comment]
Published in 0.10.5.

**Pull request merged**
