### PR TITLE
Test/externally used assets exists

### PR DESCRIPTION
**Pull request by Aierie**

### CODE REVIEW

**Comment by Aierie** [comment]
@backspace is this good to add to Percy?

**Comment by Aierie** [comment]
> Could it work as a “component” test? This implementation looks like it wouldn’t actually render anything for Percy to see 🤔 but in a component test there could be a template that renders the images

We could visit each asset's page I think

**Comment by backspace** [comment]
I think you can only `visit` routes recognised by the router:

image

Also, scarcity thinking, but it might save on our limited usage to have them all in one snapshot vs one for each 😆

**Comment by Aierie** [comment]
> I think you can only `visit` routes recognised by the router:
> 
> image
> 
> Also, scarcity thinking, but it might save on our limited usage to have them all in one snapshot vs one for each 😆

Sounds good, will work on a PR to add Percy to this

**Pull request merged**
