### PR TITLE
web: Fix Power Select auto-choosing bug

### PR DESCRIPTION
**Pull request by backspace**
When I run this locally, it fixes the problem where the prepaid
card chooser in the merchant creation workflow looks like
it’s not opening but is really selecting the first card and
closing.

Thanks to @johanrd for documenting and @Aierie for finding:
https://github.com/cibernox/ember-power-select/issues/1408

### CODE REVIEW

**Comment by backspace** [comment]
This does move the dropdown down but I think it’s worth it!

1px-screencast 2021-09-03 10-04-49

**Comment by Aierie** [comment]
This fixes one part of the issue, I think another part is the dropdown taking up space and pushing itself under the mouse as it scrolls. Wondering if we should not allow the dropdown to take up space in that way.

**Comment by Aierie** [comment]
single-click-select

This selection is done in a single click as the dropdown pushes itself up

**Review by Aierie — APPROVED** [review]

**Review by burieberry — APPROVED** [review]
It's still a bit funky for me but let's try it

**Comment by backspace** [comment]
ya further revisions are still possible of course!

**Pull request merged**
