### PR TITLE
ssr: Update Embroider to 1.3.0

### PR DESCRIPTION
**Pull request by backspace**
The CSS bug that made development builds not work has been
fixed, thanks to @simonihmig!

https://github.com/embroider-build/embroider/pull/1146

### CODE REVIEW

**Comment by backspace** [comment]
This branch has in fact been deployed, I wonder how we can register that 🤔

image

It works, so marking ready for review! 🎉

**Comment by Aierie** [comment]
I am getting some watchman-related issues when running `ember s` locally:
```

**Comment by Aierie** [comment]
I am getting some watchman-related issues when running `ember s` locally:
```
=================================================================================

ENV Summary:

  TIME: Mon Mar 07 2022 15:26:04 GMT+0800 (Malaysia Time)
  TITLE: ember
  ARGV:
  - /Users/michael/.volta/tools/image/node/14.18.3/bin/node
  - /Users/michael/Documents/cardstack/cardstack/packages/ssr-web/node_modules/.bin/ember
  - s
  EXEC_PATH: /Users/michael/.volta/tools/image/node/14.18.3/bin/node
  TMPDIR: /var/folders/rp/dy6z5rw13f9dwy943hxjsz5m0000gn/T
  SHELL: /bin/zsh
  PATH:
  - /Users/michael/.volta/tools/image/yarn/1.22.17/bin
  - /Users/michael/.volta/tools/image/node/14.18.3/bin
  - /Users/michael/.cardpay/bin
  - /Users/michael/bin
  - /Applications/Postgres.app/Contents/Versions/latest/bin
  - /Users/michael/.volta/bin/node
  - /Users/michael/.volta/bin
  - /opt/homebrew/bin
  - /opt/homebrew/sbin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /Library/Apple/usr/bin
  - /Users/michael/.cardpay/bin
  - /Users/michael/bin
  - /Applications/Postgres.app/Contents/Versions/latest/bin
  - /Users/michael/.volta/bin/node
  - /Users/michael/.volta/bin
  - /opt/homebrew/bin
  - /opt/homebrew/sbin
  - /Users/michael/.cargo/bin
  - /Users/michael/.fig/bin
  PLATFORM: darwin x64
  FREEMEM: 28577792
  TOTALMEM: 8589934592
  UPTIME: 1728
  LOADAVG: 1.8427734375,3.0322265625,6.400390625
  CPUS:
  - Apple M1 - 24
  - Apple M1 - 24
  - Apple M1 - 24
  - Apple M1 - 24
  - Apple M1 - 24
  - Apple M1 - 24
  - Apple M1 - 24
  - Apple M1 - 24
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.18.1
  - brotli: 1.0.9
  - cldr: 39.0
  - icu: 69.1
  - llhttp: 2.1.4
  - modules: 83
  - napi: 8
  - nghttp2: 1.42.0
  - node: 14.18.3
  - openssl: 1.1.1l
  - tz: 2021a
  - unicode: 13.0
  - uv: 1.42.0
  - v8: 8.4.371.23-node.85
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: EMFILE
  - codeFrame: [undefined]
  - errorMessage: EMFILE: too many open files, watch
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [null]
    - line: [undefined]
  - message: EMFILE: too many open files, watch
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:203:21)

=================================================================================
```

**Review by jurgenwerk — APPROVED** [review]
Nice, works nicely. @Aierie looks like this is an M1 related issue? Have you checked https://github.com/facebook/watchman/issues/923?

**Comment by Aierie** [comment]
> Nice, works nicely. @Aierie looks like this is an M1 related issue? Have you checked [facebook/watchman#923](https://github.com/facebook/watchman/issues/923)?

Seems possible that it's m1... 😢  I'll have a look, thanks for pointing that out

**Comment by Aierie** [comment]
Would also update the `start` script in `package.json` to not serve prod

**Comment by backspace** [comment]
I’m on an M1 too and not having Watchman problems so I guess it’s machine-specific 😢

**Pull request merged**
