### PR TITLE
Add updating of workflow count on storage event

### PR DESCRIPTION
**Pull request by backspace**
I’m opening this is a separate PR to get feedback on whether this awkwardness is worth it for getting testing around having a `storage` event trigger a recalculation of the count of restorable workflows.

The test is as close as I could get to the true situation of another tab updating `localStorage` with a newly-persisted or -updated workflow. It appends a blank `iframe` as a child of the test page and updates its `localStorage`, which will trigger the `storage` event handler in the workflow persistence service. Noteworthy is that in tests, `localStorage` isn’t even being used for workflow persistence, but this technique works to be able to react to the `storage` event, which seems hard to produce artificially.

Here it is in action:

storage-event-screencast 2021-09-29 15-29-33

### CODE REVIEW

**Comment by lukemelia** [comment]
Not worth it IMO for the reasons we discussed in Sprint planning: solves for tabs with localstorage-specific complexity and doesn't address cross-decice syncing.

**Comment by backspace** [comment]
so do you think it’s not worth having a listener for `storage` at all? Or just not have it tested?

**Comment by lukemelia** [comment]
I was thinking not to have it at all. Open to other perspectives though.

**Comment by Aierie** [comment]
I think not having it makes the workflow queue pretty confusing for someone who has multiple tabs open

**Comment by Aierie** [comment]
Thinking specifically that this is confusing:


https://user-images.githubusercontent.com/39579264/135502143-257bd9bd-d71b-476f-8094-b27235f678d3.mov

**Review by burieberry — APPROVED** [review]
Since this is already done and is working for the same browser, we might as well add it.

**Comment by lukemelia** [comment]
>Since this is already done and is working for the same browser, we might as well add it.

OK, I'm convinced.

**Pull request merged**
