### PR TITLE
fixes issue #160 - refactor checkpoint and restores

### PR DESCRIPTION
**Pull request by habdelra**

### CODE REVIEW

**Comment by ef4** [comment]
Checkpoints are already a first-class content-type -- they don't belong down inside `params` on the postgres data source. 

Looking up the checkpoint that's being restored is generic -- every data source needs the same thing. So the code for that can go in hug/writers.js:restoreCheckpoint(). The document passed into writer.prepareCheckpointRestore can be the actual checkpoint, all ready to go.

**Comment by ef4** [comment]
Yes, that should be allowed. It does mean you’ll need some place to store them that actually works. 

This is another reason I’m doing my data source routing refactor — you shouldn’t need to worry about this stuff. Merely making Postgres your default data source should take care of creating all the schema that is needed by every plugin, including test-support.

**Comment by habdelra** [comment]
so I shouldn't have to worry about having a migration script that accommodates a checkpoint table is the default data source is postgres?

**Comment by habdelra** [comment]
hmmmm, actually i'm confused why the hub:writer even has checkpoint stuff in it. checkpoints are handled by the `test-support`. and a plain create on the 'checkpoint' or 'restore' content type kicks off the whole thing. I think the hub's checkpoint stuff is no longer used and never got cleaned up when we refactored.

**Comment by ef4** [comment]
Oh yes, I was mistaken. I was confused by the vestigial code in hub:writers. You're right, all the generic parts go in the test support writer.

Let's discuss tomorrow, working backward from the API we really want for tests to use, starting with how test-support/addon/fixtures.js already works.

**Comment by habdelra** [comment]
Closing this to approach the test setup/teardown from a different direction based on our discussion

**Pull request closed without merging**
