### PR TITLE
Add containsMany editor

### PR DESCRIPTION
**Pull request by burieberry**

### CODE REVIEW

**Comment by mattmcmanus** [comment]
- [ ] Make the `ContainsManyManager` component in Boxel (for now, it's unclear how to import it from cardhost)
  - Api: 
    - `@model` the pojo
    - `@set` we return the mutated pogo
  - [ ] Manually use it in the edit view of the `links` component
  - [ ] Update component transpiling to apply that component automatically

**Comment by burieberry** [comment]
> * [ ]  Make the `ContainsManyManager` component in Boxel (for now, it's unclear how to import it from cardhost)
>   
>   * Api:
>     
>     * `@model` the pojo
>     * `@set` we return the mutated pogo
> * [ ]  Manually use it in the edit view of the `links` component
> * [ ]  Update component transpiling to apply that component automatically

The first two steps are mostly done. Editing a pojo's content doesn't quiet work, though. What I was gonna do in the component didn't seem very sophisticated and wasn't sure if I should make any changes in the `card-model` file in the core package where the `makeSetter` function resides.

**Comment by ef4** [comment]
Notes from group code review:

 - this is blocked on having an API for generating new members of the plural field (that concern doesn't belong in the contains many editor component, it belongs in the card service and will depend on the compiler)
 - this needs to get tested under the compiler, not in boxel, so we need to decide a different place to put it and how that should build

**Comment by jurgenwerk** [comment]
Closing due to inactivity.

**Pull request closed without merging**
