### PR TITLE
perform db migration as part of hub docker container starting up

### PR DESCRIPTION
**Pull request by habdelra**

### CODE REVIEW

**Comment by lukemelia** [comment]
@habdelra we boot up multiple instances of this at once. Are you concerned about race conditions? Or do you expect postgres' DDL transactions to be sufficient to smooth that over?

**Comment by habdelra** [comment]
yeah I was thinking about that. i think it's fine. the migrations are transactional, and if the migration has already run then it will just do nothing

**Comment by habdelra** [comment]
for a historical perspective, we actually used to do this in the original v1 version of the hub using the same node-pg-migrate pkg, where the hub boot process started with a migration, and we had multiple hub instances running concurrently. it worked out very nicely.

**Comment by habdelra** [comment]
For reference this is what it looks like from the waypoint logs: 
```
2022-01-07T22:55:28.665Z XSAN9Z: > Migrating files:
2022-01-07T22:55:28.666Z XSAN9Z: > - 20211214163123421_card-index-errors
2022-01-07T22:55:28.666Z XSAN9Z: > - 20220103201128435_invalidation-ordering
2022-01-07T22:55:28.666Z XSAN9Z: > - 20220107151914576_rename-beta-testers-table
2022-01-07T22:55:28.672Z XSAN9Z: ### MIGRATION 20211214163123421_card-index-errors (UP) ###
2022-01-07T22:55:28.673Z XSAN9Z: BEGIN;
2022-01-07T22:55:28.673Z XSAN9Z: DELETE FROM cards;
2022-01-07T22:55:28.673Z XSAN9Z: ALTER TABLE "cards"
2022-01-07T22:55:28.673Z XSAN9Z:   ADD "compileErrors" jsonb,
2022-01-07T22:55:28.673Z XSAN9Z:   ADD "deps" text[],
2022-01-07T22:55:28.673Z XSAN9Z:   ADD "raw" jsonb,
2022-01-07T22:55:28.673Z XSAN9Z:   ADD "compiled" jsonb;
2022-01-07T22:55:28.673Z XSAN9Z: CREATE TABLE "realm_metas" (
2022-01-07T22:55:28.673Z XSAN9Z:   "realm" text PRIMARY KEY,
2022-01-07T22:55:28.673Z XSAN9Z:   "meta" jsonb
2022-01-07T22:55:28.673Z XSAN9Z: );
2022-01-07T22:55:28.673Z XSAN9Z: INSERT INTO "public"."pgmigrations" (name, run_on) VALUES ('20211214163123421_card-index-errors', NOW());
2022-01-07T22:55:28.673Z XSAN9Z: COMMIT;
2022-01-07T22:55:28.673Z XSAN9Z:
2022-01-07T22:55:28.673Z XSAN9Z:
2022-01-07T22:55:28.689Z XSAN9Z: ### MIGRATION 20220103201128435_invalidation-ordering (UP) ###
2022-01-07T22:55:28.690Z XSAN9Z: BEGIN;
2022-01-07T22:55:28.690Z XSAN9Z: CREATE TYPE "card_dep" AS (
2022-01-07T22:55:28.690Z XSAN9Z: "url" text,
2022-01-07T22:55:28.690Z XSAN9Z: "deps" text[]
2022-01-07T22:55:28.690Z XSAN9Z: );
2022-01-07T22:55:28.690Z XSAN9Z: CREATE FUNCTION "deps_cmp"(card_dep, card_dep)
2022-01-07T22:55:28.690Z XSAN9Z:   RETURNS integer
2022-01-07T22:55:28.690Z XSAN9Z:   AS $pga$
2022-01-07T22:55:28.690Z XSAN9Z:     select case
2022-01-07T22:55:28.690Z XSAN9Z:       when $1.url = any($2.deps)
2022-01-07T22:55:28.690Z XSAN9Z:         then 1
2022-01-07T22:55:28.690Z XSAN9Z:       when $2.url = any($1.deps)
2022-01-07T22:55:28.690Z XSAN9Z:         then -1
2022-01-07T22:55:28.690Z XSAN9Z:       else
2022-01-07T22:55:28.690Z XSAN9Z:         case
2022-01-07T22:55:28.690Z XSAN9Z:           when $1.url < $2.url
2022-01-07T22:55:28.690Z XSAN9Z:             then -1
2022-01-07T22:55:28.690Z XSAN9Z:           when $2.url < $1.url
2022-01-07T22:55:28.690Z XSAN9Z:             then 1
2022-01-07T22:55:28.690Z XSAN9Z:           else
2022-01-07T22:55:28.690Z XSAN9Z:             0
2022-01-07T22:55:28.690Z XSAN9Z:           end
2022-01-07T22:55:28.690Z XSAN9Z:       end
2022-01-07T22:55:28.690Z XSAN9Z:     ;
2022-01-07T22:55:28.690Z XSAN9Z:   $pga$
2022-01-07T22:55:28.690Z XSAN9Z:   VOLATILE
2022-01-07T22:55:28.690Z XSAN9Z:   LANGUAGE sql;
2022-01-07T22:55:28.690Z XSAN9Z: CREATE FUNCTION "card_lt"(card_dep, card_dep)
2022-01-07T22:55:28.690Z XSAN9Z:   RETURNS bool
2022-01-07T22:55:28.690Z XSAN9Z:   AS $pga$select deps_cmp($1, $2) < 0;$pga$
2022-01-07T22:55:28.690Z XSAN9Z:   VOLATILE
2022-01-07T22:55:28.781Z XSAN9Z: ### MIGRATION 20220107151914576_rename-beta-testers-table (UP) ###
2022-01-07T22:55:28.781Z XSAN9Z: BEGIN;
2022-01-07T22:55:28.781Z XSAN9Z: ALTER TABLE "beta_testers" RENAME CONSTRAINT "beta_testers_pkey" TO "card_drop_recipients_pkey";
2022-01-07T22:55:28.781Z XSAN9Z: ALTER TABLE "beta_testers" RENAME TO "card_drop_recipients";
2022-01-07T22:55:28.781Z XSAN9Z: INSERT INTO "public"."pgmigrations" (name, run_on) VALUES ('20220107151914576_rename-beta-testers-table', NOW());
2022-01-07T22:55:28.781Z XSAN9Z: COMMIT;
2022-01-07T22:55:28.781Z XSAN9Z:
2022-01-07T22:55:28.781Z XSAN9Z:
2022-01-07T22:55:32.372Z 69KWR3: No migrations to run!
2022-01-07T22:55:32.611Z RVJ8MW: No migrations to run!
2022-01-07T22:55:35.988Z KKC7N0: No migrations to run!
```
Note that node-pg-migrate wraps the entire migration SQL in a transaction. when the other instances spin up they just skip the migrations

**Pull request merged**
